[package]
name = "typst-count"
author = "Mikkel M.H. Pedersen <mikkel.helding@gmail.com>"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
typst = "0.14.2"
typst-syntax = "0.14.2"
anyhow = "1.0"
